# Generated by Django 5.1.1 on 2024-10-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NestGuardContatoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField()),
                ('titulo2', models.TextField()),
                ('titulo3', models.TextField()),
                ('titulo4', models.TextField()),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('descricao3', models.TextField()),
                ('descricao4', models.TextField()),
                ('imagem1', models.ImageField(upload_to='images/')),
                ('imagem2', models.ImageField(upload_to='images/')),
                ('imagem3', models.ImageField(upload_to='images/')),
                ('imagem4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NestGuardDashboradPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField()),
                ('titulo2', models.TextField()),
                ('titulo3', models.TextField()),
                ('titulo4', models.TextField()),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('descricao3', models.TextField()),
                ('descricao4', models.TextField()),
                ('imagem1', models.ImageField(upload_to='images/')),
                ('imagem2', models.ImageField(upload_to='images/')),
                ('imagem3', models.ImageField(upload_to='images/')),
                ('imagem4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NestGuardSegurançaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField()),
                ('titulo2', models.TextField()),
                ('titulo3', models.TextField()),
                ('titulo4', models.TextField()),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('descricao3', models.TextField()),
                ('descricao4', models.TextField()),
                ('imagem1', models.ImageField(upload_to='images/')),
                ('imagem2', models.ImageField(upload_to='images/')),
                ('imagem3', models.ImageField(upload_to='images/')),
                ('imagem4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NestGuardSitesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField()),
                ('titulo2', models.TextField()),
                ('titulo3', models.TextField()),
                ('titulo4', models.TextField()),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('descricao3', models.TextField()),
                ('descricao4', models.TextField()),
                ('imagem1', models.ImageField(upload_to='images/')),
                ('imagem2', models.ImageField(upload_to='images/')),
                ('imagem3', models.ImageField(upload_to='images/')),
                ('imagem4', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NestGuardSobrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField()),
                ('titulo2', models.TextField()),
                ('titulo3', models.TextField()),
                ('titulo4', models.TextField()),
                ('descricao1', models.TextField()),
                ('descricao2', models.TextField()),
                ('descricao3', models.TextField()),
                ('descricao4', models.TextField()),
                ('imagem1', models.ImageField(upload_to='images/')),
                ('imagem2', models.ImageField(upload_to='images/')),
                ('imagem3', models.ImageField(upload_to='images/')),
                ('imagem4', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
