# Generated by Django 5.1.1 on 2024-10-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0002_nestguardcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nestguardcard',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcard',
            name='link_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcard',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='titulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='titulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='titulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardcontatopage',
            name='titulo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='titulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='titulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='titulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguarddashboradpage',
            name='titulo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='titulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='titulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='titulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsegurançapage',
            name='titulo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='titulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='titulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='titulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsitespage',
            name='titulo4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='descricao1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='descricao2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='descricao3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='descricao4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='imagem1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='imagem2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='imagem3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='imagem4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='titulo1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='titulo2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='titulo3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nestguardsobrepage',
            name='titulo4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
