# Generated by Django 5.1.1 on 2024-10-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0003_alter_nestguardcard_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestguardcard',
            name='descricaoModal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
