# Generated by Django 5.1.1 on 2024-10-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0004_nestguardcard_descricaomodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo8',
            field=models.TextField(blank=True, null=True),
        ),
    ]
