# Generated by Django 5.1.1 on 2024-10-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0005_nestguarddashboradpage_descricao5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardcontatopage',
            name='titulo9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguarddashboradpage',
            name='titulo9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsegurançapage',
            name='titulo9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsitespage',
            name='titulo9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='descricao9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem11',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem12',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem13',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem14',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='imagem9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nestguardsobrepage',
            name='titulo9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
