# Generated by Django 5.1.4 on 2024-12-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0007_delete_nestguardcontatopage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('telefone_cliente', models.CharField(max_length=15, verbose_name='Telefone do Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Serviço')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('tipo_servico', models.CharField(choices=[('criar_site', 'Criação de site'), ('criar_design', 'Criação de design'), ('criar_bot', 'Criação de bot'), ('hospedagem', 'Hospedagem'), ('automacao', 'Automação'), ('outros', 'Outros')], max_length=50, verbose_name='Tipo de Serviço')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
    ]
