# Generated by Django 5.1.6 on 2025-02-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0009_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutUs',
        ),
    ]
