# Generated by Django 5.1.6 on 2025-02-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0010_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.TextField(blank=True, null=True)),
                ('titulo2', models.TextField(blank=True, null=True)),
                ('paragrafo1', models.TextField(blank=True, null=True)),
                ('paragrafo2', models.TextField(blank=True, null=True)),
                ('paragrafo3', models.TextField(blank=True, null=True)),
                ('paragrafo4', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
