# Generated by Django 5.1.6 on 2025-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0011_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloCarrosel', models.TextField(blank=True, max_length=40, null=True)),
                ('subtituloCarrosel', models.TextField(blank=True, null=True)),
                ('carrosselImg1', models.ImageField(upload_to='imagesCarrosel/')),
                ('carrosselImg2', models.ImageField(upload_to='imagesCarrosel/')),
                ('carrosselImg3', models.ImageField(upload_to='imagesCarrosel/')),
                ('tituloSection1', models.TextField(blank=True, null=True)),
                ('subtituloSection1', models.TextField(blank=True, null=True)),
                ('tituloCard1', models.TextField(blank=True, null=True)),
                ('descricaoCard1', models.TextField(blank=True, null=True)),
                ('tituloCard2', models.TextField(blank=True, null=True)),
                ('descricaoCard2', models.TextField(blank=True, null=True)),
                ('tituloCard3', models.TextField(blank=True, null=True)),
                ('descricaoCard3', models.TextField(blank=True, null=True)),
                ('tituloSection2', models.TextField(blank=True, null=True)),
                ('textoSection2', models.TextField(blank=True, null=True)),
                ('imgSection2', models.ImageField(upload_to='imagesSection2/')),
                ('tituloSection3', models.TextField(blank=True, null=True)),
                ('textoSection3', models.TextField(blank=True, null=True)),
                ('tituloSection4', models.TextField(blank=True, null=True)),
                ('textoSection4', models.TextField(blank=True, null=True)),
                ('imgSection4', models.ImageField(upload_to='imagesSection4/')),
                ('textoSection5', models.TextField(blank=True, null=True)),
                ('tituloSection6', models.TextField(blank=True, null=True)),
                ('imgSection5', models.ImageField(upload_to='imagesSection5/')),
            ],
        ),
    ]
