# Generated by Django 5.1.6 on 2025-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0012_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='subtituloCarrosel',
            new_name='subtituloCarrosel1',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='tituloSection6',
            new_name='subtituloCarrosel2',
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtituloCarrosel3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tituloSection5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
