# Generated by Django 5.1.6 on 2025-03-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppNestGuard', '0013_rename_subtitulocarrosel_homepage_subtitulocarrosel1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email do Cliente')),
            ],
        ),
    ]
